# File: Initializer.py
"""
Playing around with a simple python program to set up all of the needed files
for a github repository. When ran, this program should do the following:
- Create a README.md file
- Prompt user for a project name and write that to the heading.
- scrub the input and create a python file with the same project name in camelCase
- Create a number of folders user requests
"""
import os
from datetime import date

today = date.today()

# I don't know how to use this yet so it's getting commented out.
# osPathPrompt = input("Where do you want this project to go?")

projectName = input("What is the name of your project?")
# Default working path on my main computer. This is probably horrendous opsec, but I can't be bothered right now. If broken, change this to correct path.
# pathLocation = r'C:\Users\jackb\Desktop\workhere\2025 Code Advent'
imagePath = r".\assets"

import os

def makeDirectories():
    while True:
        try:
            count = int(input("Enter the number of folders to create (1-5): "))
            if 1 <= count <= 5:
                break
            else:
                print("Please enter a number between 1 and 5.")
        except ValueError:
            print("Invalid input! Please enter a valid number (1-5).")

    for i in range(1, count + 1):
        folderName = f"initialFolder_{i}"
        try:
            os.mkdir(folderName)
            print(f"Folder created: {folderName}")
        except FileExistsError:
            print(f"Folder {folderName} already exists.")

def readMeFile():
    projectMarkdown = projectName.replace(" ", "-")
    f = open("README.md", 'w')
    f.write(f"""
![Project Banner]({imagePath + "\placeholder"})

# {projectName}
             
***Note** - This README was generated by './initalizer.py'.

## Demo (optional)
![Demo GIF]({imagePath + "\gif1placeholder"})

## Table of Contents (optional)

<!--ts-->
* [{projectMarkdown}](#{projectMarkdown})
* [Prerequisites](#prerequisites)
* [Installation](#installation)
* [Initial Configuration](#initial_configuration)
* [Usage](#usage)
* [Documentaion](#documentaion)
* [What's Included? (Features)](#what's_included? (features))
* [Configuration](#configuration)
* [Contributing](#contributing)
* [Links](#links)
* [Support & Maintenance](#support_&_maintenance)
* [Licensing](#licensing)
<!--te-->

## Prerequisites
Any prerequisites needed for the project.

### System Requirements:
* [git](https://git-scm.com/) >= 2.52.0

## Installation
step by step guide for installation.

### Intial Configuration
document any requirements ( `npm i`, access tokens, ect).

### Usage
instructions for developers / users on using the project after installation.

![Screenshots]({imagePath + "\screenshotplaceholder"})

## Documentation
Link to any external documentation.

## What's included?

## Configuration
Write out all of the configurations a user can enter when using the program

## Contributing
Open / Closed Contributions. list of contributors. guidelines for contributions.

## Author
Written by Jack Phillips. {today} :3

## Licensing
Any licensing disclosure.

""")
    f.close()

def gitIgnore():
    f = open(".gitignore", 'w')
    f.write("__pychache__/")
    f.close

def main():
    makeDirectories()
    readMeFile()
    gitIgnore()


if __name__ == "__main__":
    main()
